//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEU_TD
    {
        public int MATC { get; set; }
        public int SoPTDTD { get; set; }
        public Nullable<int> MucdoHoanthanh { get; set; }
        public Nullable<double> Diemso { get; set; }
    
        public virtual PHIEUTHEODOI PHIEUTHEODOI { get; set; }
        public virtual TIEUCHI TIEUCHI { get; set; }
    }
}
