//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIANGVIEN()
        {
            this.PHIEU_CHAM_DIEM = new HashSet<PHIEU_CHAM_DIEM>();
            this.PhieuGiaoDTs = new HashSet<PhieuGiaoDT>();
        }
    
        public int MAGV { get; set; }
        public string HOGV { get; set; }
        public string TENGV { get; set; }
        public string QUEQUAN { get; set; }
        public string ANHDAIDIEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> TRANGTHAIGV { get; set; }
        public Nullable<int> MADV { get; set; }
        public Nullable<int> MACV { get; set; }
        public Nullable<int> MAHV { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual DONVI DONVI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_CHAM_DIEM> PHIEU_CHAM_DIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuGiaoDT> PhieuGiaoDTs { get; set; }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }

        public virtual HOCVI HOCVI { get; set; }
    }
}
