//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHEODOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTHEODOI()
        {
            this.CT_PHIEU_TD = new HashSet<CT_PHIEU_TD>();
        }
    
        public int SoPTDTD { get; set; }
        public int SoPGDT { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public string HinhThuc_Gap_GV { get; set; }
        public Nullable<int> MUCDO_HOANTHANH_CHUNG { get; set; }
        public Nullable<double> DIEM_THEODOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_TD> CT_PHIEU_TD { get; set; }
        public virtual PhieuGiaoDT PhieuGiaoDT { get; set; }
    }
}
