//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCHOOLMANAGEMENTEntities : DbContext
    {
        public SCHOOLMANAGEMENTEntities()
            : base("name=SCHOOLMANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CT_PHIEU_TD> CT_PHIEU_TD { get; set; }
        public virtual DbSet<DETAI> DETAIs { get; set; }
        public virtual DbSet<DONVI> DONVIs { get; set; }
        public virtual DbSet<HOCVI> HOCVIs { get; set; }
        public virtual DbSet<LOAIDT> LOAIDTs { get; set; }
        public virtual DbSet<PHIEU_CHAM_DIEM> PHIEU_CHAM_DIEM { get; set; }
        public virtual DbSet<PhieuGiaoDT> PhieuGiaoDTs { get; set; }
        public virtual DbSet<PHIEUTHEODOI> PHIEUTHEODOIs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<TIEUCHI> TIEUCHIs { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
    }
}
